name: Deploy to Github Pages
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Cache Hugo resources
        uses: actions/cache@v3
        env:
          cache-name: cache-hugo-resources
        with:
          path: resources
          key: '${{ env.cache-name }}'
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.17.0
      - run: go version
      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: '${{ runner.os }}-go-${{ hashFiles(''**/go.sum'') }}'
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: '${{ runner.os }}-hugomod-${{ hashFiles(''**/go.sum'') }}'
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: Build
        run: hugo --minify --enableGitInfo --gc
      - name: "Deploy \U0001F680"
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/master'
        with:
          branch: site
          folder: public
          clean: true
          single-commit: true
